[project]
name = "obsidianknowledgecurator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "mcp>=1.27.1",
    "pydantic>=2.13.4",
    "pypdf>=6.12.2",
    "requests>=2.34.2",
    "websocket-client>=1.8.0",
    "youtube-transcript-api>=1.2.4",
    "yt-dlp>=2026.3.17",
    "marker-pdf",
    "watchdog>=4.0.0",
    "firecrawl-anydoc",
]

